// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqx8khH95tnQpz5WfTqTJQQzsPeLhH63I',
    appId: '1:914199632725:web:00b0afbbb6e569d2f66ddc',
    messagingSenderId: '914199632725',
    projectId: 'crosstech-ef31d',
    authDomain: 'crosstech-ef31d.firebaseapp.com',
    databaseURL: 'https://crosstech-ef31d-default-rtdb.firebaseio.com',
    storageBucket: 'crosstech-ef31d.appspot.com',
    measurementId: 'G-2NFHJQWL1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdoj93qCIy7SDVEyKUTjv_g4KwnVxeF9I',
    appId: '1:914199632725:android:be981d19c04451fff66ddc',
    messagingSenderId: '914199632725',
    projectId: 'crosstech-ef31d',
    databaseURL: 'https://crosstech-ef31d-default-rtdb.firebaseio.com',
    storageBucket: 'crosstech-ef31d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL75nPlN38VTBI6sIjxZHxEdNQdm_kZUY',
    appId: '1:914199632725:ios:3e902eb92246d8eaf66ddc',
    messagingSenderId: '914199632725',
    projectId: 'crosstech-ef31d',
    databaseURL: 'https://crosstech-ef31d-default-rtdb.firebaseio.com',
    storageBucket: 'crosstech-ef31d.appspot.com',
    iosClientId: '914199632725-0hv4b1656ik13gc4l951qmrnvb21dfnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.crossTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL75nPlN38VTBI6sIjxZHxEdNQdm_kZUY',
    appId: '1:914199632725:ios:c56bef1bd21e19a3f66ddc',
    messagingSenderId: '914199632725',
    projectId: 'crosstech-ef31d',
    databaseURL: 'https://crosstech-ef31d-default-rtdb.firebaseio.com',
    storageBucket: 'crosstech-ef31d.appspot.com',
    iosClientId: '914199632725-3pork2sceeqevmi7t2i1nk4f15f8crnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.crossTech.RunnerTests',
  );
}
